### ISSUE TITLE
Restore Cookie and Luke's greeting methods

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601-S20/lab-0-intro-to-git-everyone#2]
:bangbang: Commit a15948488b68b488ed109216c85dce798815081e broke the build by deleting the greeting methods from @CookieVang7 and @burde041. Those methods are still called in `main()`, so this code currently doesn't even compile. :cry:

**Comment by NicMcPhee** [comment]
Here's a screen shot of the state of when I found the build broken:

![Screen Shot 2020-01-21 at 3 32 35 PM](https://user-images.githubusercontent.com/302297/72845362-0c5c6780-3c64-11ea-9fc2-0f267bd9571a.png)

Looking at [the commit history](https://github.com/UMM-CSci-3601-S20/lab-0-intro-to-git-everyone/commits/master) suggests that this is where things went bad as we go from a passing commit (on the bottom) to a passing one on the top.

![Screen Shot 2020-01-21 at 3 39 11 PM](https://user-images.githubusercontent.com/302297/72845441-4168ba00-3c64-11ea-94c7-b3eab8f20c29.png)

The problem is, in fact, the middle commit (a15948488b68b488ed109216c85dce798815081e). It doesn't have a red x or a green check because the next commit came in so fast that GitHub didn't even bother checking the first of those two commits. If you look at [the changes on that commit](https://github.com/UMM-CSci-3601-S20/lab-0-intro-to-git-everyone/commit/a15948488b68b488ed109216c85dce798815081e) then you'll see that that commit removes @CookieVang7 and @burde041's greetings methods, which means the code doesn't compile anymore. :cry:

**Comment by kklamberty** [comment]
@NicMcPhee closed this issue in commit fe78b11429e8cf10045d3b600b4eb8891e151627

**Comment by NicMcPhee** [comment]
Thanks for cleaning this up for me. I totally should have included the "close" message in that commit so it automatically connected to this. Ooops.
